JuegoRuleta/Models/ErrorViewModel.cs
namespace JuegoRuleta.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

JuegoRuleta/Models/Jugador.cs
using System.ComponentModel.DataAnnotations;

namespace JuegoRuleta.Models{

    public class Jugador{

        [Key]
        public required string NombreCompleto { get; set; }

        public required decimal Saldo { get; set; }


    }

}

JuegoRuleta/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using JuegoRuleta.Models;

namespace JuegoRuleta.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

JuegoRuleta/Controllers/JuegoController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using JuegoRuleta.Models;
using Vetmania.Data;

namespace JuegoRuleta.Controllers;

public class JuegoController : Controller
{
    private readonly ILogger<JuegoController> _logger; 
    private AppDbContext _contexto;

    public JuegoController(ILogger<JuegoController> logger, AppDbContext contexto)
    {
        _logger = logger;
        _contexto = contexto;
    }

    public IActionResult Index()
    {
        return View();
    }



    public JsonResult GuardarJugador(string NombreJugador, decimal Saldo)
    {
        int resultado = 0;


        var Jugador = _contexto.Jugadores.Where(j => j.NombreCompleto == NombreJugador).FirstOrDefault();

        if (Jugador == null)
        {

            var AgregarJugador = new Jugador
            {
                NombreCompleto = NombreJugador,
                Saldo = Saldo
            };
            _contexto.Add(AgregarJugador);
            _contexto.SaveChanges();
            resultado = 1;
        }
        else
        {

            Jugador.Saldo = Saldo;
            _contexto.SaveChanges();
            resultado = 2;
            
        }


        return Json(resultado);
    }



}

JuegoRuleta/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Inicio";
}

<style>
    body {
        background-image: linear-gradient( rgba(0, 0, 0, 0.253), rgb(0, 0, 0)), url(../img/roleta.jpg);
        background-repeat: no-repeat;
        background-size: cover;
        background-position: center;s
        height: 100vh;
    }


    .text-center {
        position: absolute;
        color: rgb(255, 240, 0);
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
</style>

<div class="text-center">
    <h1 class="display-4">Bienvenido</h1>
</div>

JuegoRuleta/Views/Juego/Index.cshtml
@{
    ViewData["Title"] = "Juego de la ruleta";
}


<style>
        body {
            background-color: #f8f9fa;
        }
        .casino-container {
            margin-top: 50px;
            padding: 20px;
            background-color: #5e5b5b; 
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0,0,0,0.1);
        }
        h1 { 
            color: #ffcc00; 
        }
        h5 { 
            color: #ffa3a3; 
        }
        p {
            color: #000000; 
        }
        .form-control, .btn {
            margin-bottom: 10px;
        }
        .btn-info {
            background-color: #ffcc00;
            border-color: #ffcc00;
            color: #1b1b1b;
        }
        .btn-success {
            background-color: #28a745;
            border-color: #28a745;
        }
        .btn-success:hover {
            background-color: #218838;
            border-color: #1e7e34;
        }
        .btn-info:hover {
            background-color: #e6b800;
            border-color: #e6b800;
        }
        .text-center {
            text-align: center;
        }
        #resultado {
            font-weight: bold;
            font-size: 1.5em;
        }
        .rojo {
            color: red;
        }
        .negro {
            color: #010101; 
        }
        .verde {
            color: green;
        }
</style>

<body>
    <div class="container casino-container">
        <div class="row d-flex align-items-center form-inline">
            <h5>PRIMERO DEBES INGRESAR TUS DATOS PARA PODER GIRAR LA RULETA</h5>
            <div class="col-lg-5 col-md-5 col-sm-5">
                <input type="text" class="form-control input-validar" id="NombreJugador" maxlength="80" required placeholder="Nombre y Apellido"/>  
            </div>
            <div class="col-lg-5 col-md-5 col-sm-5">
                <input type="number" class="form-control input-validar" id="Saldo" maxlength="13" required placeholder="Saldo" />  
            </div>
            <div class="col-lg-2 justify-content-end">
                <button type="button" title="Guardar Jugador" class="btn btn-info" onclick="GuardarJugador()">Guardar</button>
            </div>
        </div>
        <hr>
        <div class="text-center">
            <h1>Ruleta de Casino</h1>
            <p>Saldo: <span id="saldo_consultar">0</span> créditos</p>
            <p>Introduce tu apuesta:</p>
            <input type="number" class="form-control" id="montoApuesta" placeholder="Monto de la apuesta">
            <input type="text" class="form-control" id="apuesta" placeholder="Número, color, par/impar">
            <button type="button" title="Girar Ruleta" class="btn btn-success" onclick="girarRuleta()">Girar Ruleta</button>

            <div id="resultado" class="mt-3"></div>
            <div id="apuestaResultado" class="mt-3"></div>
        </div>
    </div>

</body>

    @section Scripts {
        <script src="~/js/juego-1.0.js"></script>
    }

JuegoRuleta/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> @ViewData["Title"]</title>
    <link rel="icon" href="~/img/ruleta.png" type="image/png">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/JuegoRuleta.styles.css" asp-append-version="true" />
      <style>
        .navbar-dark {  
        background-color: #212529;  
        color: #fff;  
        }
  </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3" >
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 ">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Juego" asp-action="Index">Juego</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - JuegoRuleta - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
   

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>